var MENU=[
 {grp:'Genel bakış',items:[{id:'home',ad:'Genel bakış',tip:'home'}]},
 {grp:'Satış',items:[
  {id:'talepler',ad:'Talepler (tek kuyruk)',d:'Site, WhatsApp, mail, telefon, sosyal medya, B2B — tek kuyruk. Durum: yeni → yanıtlandı → teklif → opsiyon → rezervasyon → kaybedildi. Satış YZ okur, misafiri eşler, ilk yanıtı taslak yazar, takip planlar.'},
  {id:'teklifler',ad:'Teklifler',d:'Teklif kartı, sürümler, misafir linki, kabul → dosya. Bireysel/grup anlık fiyat; okul/kurum/private/MICE simülasyonla, onaya düşer.'},
  {id:'grupteklif',ad:'Grup & kurumsal teklifler',d:'Okul (öğretmen free, veli formu), kurum/dernek, private program tasarımı, MICE, senaryo karşılaştırma (3/4/5 yıldız, otobüs/uçak).'},
  {id:'dosya',ad:'Rezervasyonlar / dosyalar',src:'../panel/islem/?embed=1&v=dosya',d:'Dosya kartı: yolcular, odalar, istisnalar, ödeme planı, belgeler, zaman çizelgesi; opsiyon → kapora → kesin; değişiklik ve iptal-iade.'},
  {id:'misafirler',ad:'Misafirler (misafir kartları)',d:'Kişi/kurum misafir kartı, zaman çizelgesi, segmentler, KVKK rıza; YZ mükerrer birleştirme ve eksik tamamlama.'},
  {id:'b2b',ad:'B2B acenteler (Faz 1: MVP)',d:'Faz 1: acente net/komisyonlu fiyatı görür, talep ve isim listesi atar. Faz 2: cari ve hakediş. Acente kartı, komisyon/net fiyat, acente paneli (fiyat listesi, rezervasyon, ekstre), hakediş.'},
  {id:'b2e',ad:'B2E kurumsal programlar',d:'Kurum anlaşması, çalışanlara özel fiyat/kod, kapalı vitrin.'},
  {id:'kampanya',ad:'Kampanyalar, kuponlar, sadakat',d:'Kampanya (dönem, kapsam, indirim), kupon kodları, sadakat puanı kuralları.'}]},
 {grp:'Ürünler',items:[
  {id:'turlar',ad:'Turlar (katalog & seferler)',src:'../panel/islem/?embed=1&v=paket',d:'Ürün kartı, program (TR/EN/AR), ön paket, seferler, varyantlar (bireysel/grup/okul/kurum/private, muhafazakâr, seviye), kategoriler, yayın.'},
  {id:'umre',ad:'Umre & helal turlar',d:'Ayrı marka ve site (umre.plusiva.com, geçici). Umre programları, helal tatil, Nusuk/vize, din görevlisi, marka kararı.'},
  {id:'oteller',ad:'Oteller',d:'Otel kartları, tekil otel satış sayfaları, fiyat listeleri (sezon/oda/pansiyon/çocuk).'},
  {id:'transfer',ad:'Transferler',d:'Araç tipleri, güzergâh fiyatları, havalimanı karşılama, tek başına satış.'},
  {id:'ucak',ad:'Uçak & biletleme',d:'Grup bilet talebi, PNR, bilet kesme, iade/değişiklik; bireysel bilet kanalı.'},
  {id:'vize',ad:'Vize hizmetleri',d:'Ülke bazlı evrak listeleri, randevu takibi, dosya durumu, ücretler, evrak hatırlatma.'},
  {id:'cruise',ad:'Cruise',d:'Gemi/kabin, liman programı, ön ödeme/iptal kuralları, gemi + kara paketleri.'},
  {id:'okulturu',ad:'Doğa & okul turları',d:'Programlar, öğretmen free, veli formu, otobüs planı, güvenlik kuralları.'},
  {id:'incoming',ad:'Incoming (DMC)',d:'Faz 1 MENA (Arap) pazarı, Avrupa Faz 2; EN/AR programlar ve fiyat listeleri; yabancı acente kontratları; private MENA.'},
  {id:'mice',ad:'MICE & özel gruplar',d:'Toplantı/kongre/teşvik; salon, ekipman, gala, transfer, konaklama blokları; plusiva.org.tr işleri.'},
  {id:'fiyatkural',ad:'Fiyatlandırma kuralları',src:'../panel/islem/?embed=1&v=fiyat',d:'Kâr/free/kademe/kur/çocuk/kanal/segment kuralları; fiyat motoru.'},
  {id:'sezon',ad:'Fiyat listeleri & sezonlar',d:'Sezon tanımları, dönem farkları, geçerlilik, toplu güncelleme.'}]},
 {grp:'Operasyon',items:[
  {id:'takvim',ad:'Sefer takvimi',d:'Aylık/haftalık: kalkış/dönüş, karar tarihleri, ekip ve araç atamaları, çakışma uyarıları.'},
  {id:'seferdosya',ad:'Sefer dosyaları',d:'Yolcu/rooming/uçuş listeleri, atamalar, tedarikçi listeleri, program kitapçığı, kontrol listeleri (T-30/14/7/1).'},
  {id:'kurgu',ad:'Tur maliyeti · kurgu',src:'../panel/kurgu/?embed=1'},
  {id:'kontrat_aday',ad:'Tur maliyeti · adaylar',src:'../panel/kontrat/?embed=1'},
  {id:'sim',ad:'Tur maliyeti · simülasyon',src:'../panel/sim/?embed=1'},
  {id:'asama',ad:'Tur maliyeti · 3 aşama',src:'../panel/islem/?embed=1&v=tur'},
  {id:'alt',ad:'Tur maliyeti · alternatifler',src:'../panel/islem/?embed=1&v=alt'},
  {id:'teyit',ad:'Tedarikçi rezervasyonları & teyitler',d:'Rezervasyon talebi (şablon, YZ), teyit takibi, teyit yoksa uyarı, değişiklik/iptal bildirimi.'},
  {id:'ekip',ad:'Rehber & ekip planlama',d:'Havuz, uygunluk, atama önerisi, yevmiye/harcırah/avans, brifing dosyası.'},
  {id:'biletsigorta',ad:'Biletleme & sigorta',d:'Yolcu listesinden bilet kesimi, PNR, seyahat/iptal sigortası poliçesi; belgeler misafir paneline.'},
  {id:'voucher',ad:'Vouchers & belgeler',d:'Voucher (link+token), misafir/tedarikçi belgeleri, PDF şablonları (marka, dil).'},
  {id:'saha',ad:'Saha (tur sırasında)',d:'Ek gider (fiş fotoğrafı), olay bildirimi, şikayet, tur kapama ve harcama raporu.'},
  {id:'kriz',ad:'Kriz & acil durum',d:'Protokoller (hastalık, kayıp, kaza, iptal, afet), acil iletişim, kriz kaydı.'}]},
 {grp:'Tedarik & kontratlar',items:[
  {id:'tedarikci',ad:'Tedarikçi kartları & bölge ağacı',d:'Ülke → bölge → şehir → hizmet tipi; kart, durum (aday → yazışıldı → teklif → kontratlı), toplu araştırma görevi.'},
  {id:'kontratlar',ad:'Kontratlar & fiyat kartları',src:'../panel/kontrat/?embed=1'},
  {id:'yazisma',ad:'Tedarikçi yazışmaları',d:'Şablonlar (TR/EN/AR): sezon fiyat talebi, spot, rezervasyon, teyit, değişiklik, iptal; gönderim onayı.'},
  {id:'tedpuan',ad:'Tedarikçi puanları',d:'Tur sonrası değerlendirme, sorun kayıtları, teyit süresi, fiyat tutarlılığı.'}]},
 {grp:'Muhasebe & finans',items:[
  {id:'tahsilat',ad:'Tahsilatlar',d:'Ödeme planı, sanal POS, havale eşleştirme, ödeme linki, hatırlatma, makbuz; para birimi bazlı.'},
  {id:'odeme',ad:'Ödemeler (tedarikçi & ekip)',d:'Kontrat koşulundan plan, vadeler, ödeme onayı, havale kaydı, rehber avans/harcırah.'},
  {id:'fatura',ad:'Faturalar',d:'Satış faturası (e-fatura/e-arşiv; hizmet bitince taslak → onay), gelen fatura okuma ve eşleme, B2B komisyon faturası.'},
  {id:'cari',ad:'Cari hesaplar',src:'../panel/islem/?embed=1&v=cari'},
  {id:'kasa',ad:'Kasa & banka',d:'Hesaplar (TRY/EUR/USD/SAR), ekstre aktarımı ve eşleştirme, nakit kasa.'},
  {id:'kur',ad:'Kur & döviz',d:'TCMB günlük kur, marj, sefer bazlı sabitleme, kur farkı.'},
  {id:'onmuhasebe',ad:'Ön muhasebe & entegrasyon',d:'Mikro/Luca/e-defter aktarım, hesap planı, mali müşavir paketleri; marka/masraf yeri boyutu.'},
  {id:'butce',ad:'Bütçe & nakit akışı',d:'Aylık bütçe, tahmini nakit akışı, sefer bazlı nakit ihtiyacı.'},
  {id:'finrapor',ad:'Finans raporları',d:'Sefer kâr-zarar (plan/atanan/gerçek), sezon, ürün, kanal, tedarikçi maliyet analizi.'}]},
 {grp:'Pazarlama & site',items:[
  {id:'siteler',ad:'Siteler',d:'Her site ayrı çalışma alanı: kimlik (dil/para/pazar/kanal), sayfalar, vitrin, anahtar kelimeler & SEO, kampanyalar, görseller, formlar, analitik, yasal, yayın. Siteler: plusiva.com, Kültür gezileri, umre, Artı Tatil, incoming, sağlık, doğa/okul, otel sayfaları, MICE, B2B portalı.'},
  {id:'sayfalar',ad:'Sayfalar & vitrinler',d:'Ana sayfa, kategori, tur detay şablonları (T1/T2/T3), otel, kampanya, yasal; vitrin kuralları; "turu kendine göre şekillendir" bloğu.'},
  {id:'seo',ad:'Anahtar kelimeler & SEO',d:'Dil bazlı kelime listeleri, başlık/açıklama, yapılandırılmış veri, site haritası, sıralama takibi, blog.'},
  {id:'marka',ad:'Marka & tasarım',d:'Marka kitleri, ev görsel stili, şablon kütüphanesi, belge şablonları.'},
  {id:'icerik',ad:'İçerik (TR/EN/AR)',d:'Program metinleri, dahil/hariç, otel açıklamaları, destinasyon yazıları; çeviri ve tutarlılık.'},
  {id:'gorsel',ad:'Görseller & video',src:'../panel/gorsel/?embed=1'},
  {id:'reklam',ad:'Reklam & sosyal medya',d:'Google/Meta kampanyaları (bütçe onayı), UTM, paylaşım takvimi, ilan siteleri.'},
  {id:'analitik',ad:'Analitik & SEO merkezi',d:'Tüm sitelerin trafik, dönüşüm, sıralama, teknik hata görünümü.'},
  {id:'yayin',ad:'Yayın & alan adları',d:'Yayın kuyruğu, alan adı yönlendirmeleri, DNS/SSL, robots, sürüm geri alma.'}]},
 {grp:'İletişim',items:[
  {id:'gelenkutusu',ad:'Gelen kutusu (tek akış)',src:'../panel/islem/?embed=1&v=olay',d:'Mail + WhatsApp + form + DM + telefon; konuya bağlama, sınıflandırma, çıkarım, yanıt taslağı; dilinde yanıt.'},
  {id:'sablonlar',ad:'Şablonlar',d:'Misafir, tedarikçi, B2B, incoming şablonları; TR/EN/AR.'},
  {id:'bildirim',ad:'Otomatik bildirimler',d:'Tetikleyiciler (rezervasyon, ödeme, vade, T-3, uçuş, anket, doğum günü); WhatsApp/SMS/mail; günlük.'},
  {id:'telefon',ad:'Telefon & görüşme notları',d:'Arama kaydı, not, aksiyon; sesli not → metin.'},
  {id:'cikarim',ad:'Yapay zekâ çıkarımları',d:'Mesajdan çıkan veri, doğrulama, bulguyla ilişki, düzeltme.'}]},
 {grp:'Misafir ilişkileri',items:[
  {id:'misafirpanel',ad:'Misafir paneli',d:'Giriş (link/token/Google), dosyalarım, belgeler, ödeme, program, dil.'},
  {id:'sikayet',ad:'Şikayet & talep takibi',d:'Kayıt, öncelik, çözüm süresi, tazmin/iade onayı, kök neden.'},
  {id:'anket',ad:'Anketler & yorumlar',d:'Dönüş anketi, puanlar, yorum yayın onayı, tedarikçi puanına akış.'},
  {id:'sadakat',ad:'Sadakat',d:'Puan, kullanım, tekrar misafir kampanyaları.'},
  {id:'sss',ad:'SSS & bilgi bankası',d:'Yapay zekâ yanıt kaynağı; misafir sorularının cevap havuzu.'}]},
 {grp:'İnsan kaynağı',items:[
  {id:'kadro',ad:'Kadro & rehberler',d:'Ofis, rehberler, kaptanlar, yerel rehberler, serbest; belgeler, tarife, banka, uygunluk.'},
  {id:'iktakvim',ad:'Takvim, görev, izin',d:'Uygunluk takvimi, tur atamaları, izinler.'},
  {id:'avans',ad:'Avans & harcırah',d:'Avans/harcırah kayıtları, muhasebe bağı.'},
  {id:'performans',ad:'Performans & eğitim',d:'Tur puanları, yorumlar, uyarılar, el kitabı, kriz eğitimi.'}]},
 {grp:'Hukuk & uyum',items:[
  {id:'sozlesme',ad:'Sözleşmeler & yasal metinler',d:'Paket tur, mesafeli satış, ön bilgilendirme, KVKK, çerez, B2B, tedarikçi, incoming; e-onay kayıtları.'},
  {id:'tursab',ad:'TÜRSAB & sigorta',d:'Belge, DDS, bildirimler, seyahat güvence; zorunlu ve seyahat sigortaları.'},
  {id:'iptalkural',ad:'İptal-iade kuralları',d:'Ürün bazlı kurallar, yasal süreler, tüketici şikayeti dosyaları.'},
  {id:'mevzuat',ad:'Mevzuat & yurt dışı gereklilikler',d:'Vergi/fatura, Schengen, Suudi, ETIAS; YZ mevzuat takibi.'}]},
 {grp:'Denetim & kalite',items:[
  {id:'bulgular',ad:'Bulgular',src:'../panel/islem/?embed=1&v=bulgu'},
  {id:'kontrollistesi',ad:'Kontrol listeleri',d:'Sefer öncesi/sonrası, dosya kapama, ay sonu muhasebe.'},
  {id:'kalite',ad:'Kalite puanları',d:'Sefer, tedarikçi, rehber, memnuniyet.'},
  {id:'olaygunlugu',ad:'Olay günlüğü',d:'Her değişiklik, kim/ne zaman; denetleyici kuralları ve eşikleri.'}]},
 {grp:'Yapay zekâ ekibi',items:[
  {id:'kadroyz',ad:'Kadro kartları',d:'Satış, Rezervasyon, Operasyon, Tedarik, Muhasebe, Pazarlama, İletişim, Misafir ilişkileri, İK, Hukuk, Denetleyici, AR-GE, Raporlama, Güvenlik, Yapıcı: görev listesi, yetki, onay sınırı.'},
  {id:'gorevkuyrugu',ad:'Görev kuyruğu & onaylar',src:'../panel/islem/?embed=1&v=onay'},
  {id:'yetenekler',ad:'Yetenekler × sektör',src:'../panel/islem/?embed=1&v=kurulum'},
  {id:'tetik',ad:'Tetikleyiciler & onay kuralları',d:'Olay → görev kuralları, eşikler.'},
  {id:'yzgunluk',ad:'Yapay zekâ günlüğü',d:'Yapılan işler, API maliyeti, hatalar.'},
  {id:'yapici',ad:'Yapıcı ile konuş',d:'Panel içinden sohbet penceresi; sistem durumu ve kurulum listesi.'}]},
 {grp:'AR-GE',items:[
  {id:'fikir',ad:'Yeni ürün & pazar araştırması',d:'Fikirler, talep sinyalleri, sezon planı.'},
  {id:'rakip',ad:'Rakip fiyat takibi',d:'Aynı destinasyon fiyatları (güncel ilan kuralı), konumlandırma.'},
  {id:'destinasyon',ad:'Destinasyon dosyaları',d:'Yerler, müzeler, ücretler, saatler, mevsim notları.'},
  {id:'teknoloji',ad:'Teknoloji araştırmaları',d:'Görsel üretim, WhatsApp, POS, e-fatura sağlayıcıları.'}]},
 {grp:'Raporlar',items:[
  {id:'rsatis',ad:'Satış & doluluk',d:'Ciro, dosya, kişi; ürün/kanal/pazar/marka/segment; doluluk ve iptal.'},
  {id:'rkar',ad:'Kârlılık',d:'Sefer/ürün/sezon; plan-atanan-gerçek.'},
  {id:'rkanal',ad:'Kanal & tedarikçi performansı',d:'Kanal dönüşümü, tedarikçi fiyat/teyit/sorun.'},
  {id:'rmusteri',ad:'Misafir & pazarlama',d:'Tekrar oranı, memnuniyet, şikayet; trafik, dönüşüm, reklam maliyeti.'},
  {id:'rabonelik',ad:'Rapor abonelikleri',d:'Günlük/haftalık mail, dışa aktarım.'}]},
 {grp:'Güvenlik & veri',items:[
  {id:'yedek',ad:'Yedekler',d:'Günlük yedek, geri yükleme testi.'},
  {id:'erisim',ad:'Erişim & oturumlar',d:'Roller, iki adımlı doğrulama, oturum kayıtları, başarısız girişler.'},
  {id:'anahtarlar',ad:'Anahtarlar (Vault)',d:'Gizli anahtar listesi (ad/tarih), rotasyon hatırlatması.'},
  {id:'kvkk',ad:'KVKK teknik',d:'Saklama süreleri, silme talepleri, veri envanteri, denetim izi.'}]},
 {grp:'Geçiş & veri taşıma',items:[
  {id:'aktarim',ad:'Aktarım durumu',d:'Foto paneli (TAMAM), plusiva.org.tr paneli, MICE paneli, otel paneli, tour-builder, promosyon paneli, listeler.'},
  {id:'yonlendirme',ad:'Alan adı yönlendirmeleri',d:'Eski adres → yeni adres; eski anahtarların kapatılması.'}]},
 {grp:'Yönetim',items:[
  {id:'kullanicilar',ad:'Kullanıcılar & roller',src:'../panel/kullanicilar/?embed=1'},
  {id:'markalar',ad:'Markalar & kurumsal yapı',d:'Plusiva Travel, Artı Tatil, Kültür Turları, umre markası; logo, renk, iletişim, imza (marka adı); çatı marka.'},
  {id:'sirket',ad:'Şirket bilgileri',d:'Unvan, vergi, adres, TÜRSAB, banka, POS.'},
  {id:'entegrasyon',ad:'Entegrasyonlar',d:'WhatsApp, mail, POS, e-fatura, ImageKit, YouTube, Google giriş, TCMB, Paximum, Mikro, Google Ads/Meta.'},
  {id:'ayarlar',ad:'Ayarlar & boyutlar',tip:'ayarlar'},
  {id:'kurulum',ad:'Kurulum durumu',src:'../panel/islem/?embed=1&v=kurulum'},
  {id:'kararlar',ad:'Kararlarım & fikirler',src:'../panel/kararlar/?embed=1',d:'Bekleyen kararlar (A–E), çelişkiler, fikir havuzu (@Dxx etiketli), dokümanların tek kaynağı. Yapıcı buradan okur ve uygular.'}]}
];
